# Generated by Django 3.0.8 on 2021-02-25 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0003_auto_20210225_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='experience',
            name='company',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='experience',
            name='employmentType',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='experience',
            name='fieldOfwork',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='experience',
            name='state',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='experience',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
